python /home/Users/dqy/Projects/ConCutMix/main.py --data /home/Users/dqy/Dataset/ImageNet100/images/ \
  --lr 0.1 -p 300 --epochs 100 \
  --arch resnet50 \
  --use_norm \
  --wd 5e-4 \
  --cos \
  --cl_views sim-sim\
  --batch-size 256\
  --tau 0.99\
  --root_log "/home/Users/dqy/Projects/ConCutMix/log"\
  --l_d_warm 70\
  --scaling_factor 200 255 \
  --topk 30\
  --dataset ImageNet100\
  --file_name baseline \
  --num_classes 100\
  --imb_factor 1\